### ISSUE TITLE
spinners are different sizes

### ISSUE THREAD

**Issue by bcardarella** [DockYard/station-ui#14]
The `spinner` and `spinner_double` are two different default sizes and they should probably have the same default size

**Comment by bcardarella** [comment]
Example
<img width="227" alt="Screenshot 2024-11-15 at 5 18 22 PM" src="https://github.com/user-attachments/assets/3d4e5558-4346-48c4-a8eb-2f83a61f17d0">

**Comment by TheFirstAvenger** [comment]
I believe the original reasoning behind this was that the single spinner is designed to be a smaller spinner for use in places where the second inner spinner was unnecessary or too small, and the double spinner is designed to be a larger spinner (e.g. full page).
